call_parentheses = "Always"
# allow_single_line_if = true
indent_type = "Spaces"
collapse_simple_statement = "Always"
quote_style = "AutoPreferDouble"

indent_width = 2
column_width = 120

[sort_requires]
enabled = true
